name: "Git Version"
description: "Setup and Execute GitVersion"
outputs:
  nuGetVersion:
    description: "nuGetVersion"
    value: ${{ steps.gitversion.outputs.nuGetVersion }}
  semVer:
    description: "semVer"
    value: ${{ steps.gitversion.outputs.semVer }}
runs:
  using: "composite"
  steps:
    - name: "Setup .NET 6"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0.x"
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: "5.x"
    - id: gitversion
      name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
